fos_elastica:
    clients:
        default: { host: %elastic_host%, port: %elastic_port% }
    indexes:
        shlml:
            client: default
            types:
                document:
                    mappings:
                        content: ~
                        public: ~
                    persistence:
                        driver: orm
                        model: SHLML\CoreBundle\Entity\Document
                        #elastica_to_model_transformer:
                         #   query_builder_method: createSearchQueryBuilder
                        finder: ~
                        provider: ~
                        listener: ~
                word:
                    mappings:
                        content: ~
                    persistence:
                        driver: orm
                        model: SHLML\CoreBundle\Entity\Word
                        finder: ~
                        provider: ~
                        listener: ~