shlml_admin:
    resource: "@SHLMLAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

shlml_core:
    resource: "@SHLMLCoreBundle/Resources/config/routing.yml"
    prefix:   /

shlml_user:
    resource: "@SHLMLUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
