services:
    sonata.admin.book:
        class: SHLML\CoreBundle\Admin\BookAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Book" }
        arguments:
            - ~
            - SHLML\CoreBundle\Entity\Book
            - ~
        #calls:
        #    - [ setTranslationDomain, [AcmeDemoBundle]]

    sonata.admin.document:
        class: SHLML\CoreBundle\Admin\DocumentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Document" }
        arguments:
            - ~
            - SHLML\CoreBundle\Entity\Document
            - ~
        #calls:
        #    - [ setTranslationDomain, [AcmeDemoBundle]]